/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  safelist: [
    'min-h-screen',
    'flex',
    'items-center',
    'justify-center',
    'bg-gradient-to-br',
    'from-blue-50',
    'to-purple-50',
    'max-w-md',
    'w-full',
    'mx-4',
    'bg-white',
    'rounded-2xl',
    'shadow-xl',
    'p-8',
    'text-3xl',
    'font-bold',
    'text-gray-900',
    'mb-2',
    'text-gray-600',
    'text-sm',
    'font-medium',
    'text-gray-700',
    'mb-1',
    'px-4',
    'py-2',
    'border',
    'border-gray-300',
    'rounded-lg',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}